### ISSUE TITLE
Please add Release tags

### ISSUE THREAD

**Issue by fmunteanu** [crate/cratedb-prometheus-adapter#10]
With Releases, you can provide links to binary files, as well release notes describing your changes. Please add one, to facilitate rpm packaging as well.

**Comment by cparedes** [comment]
+1 on this, especially for Docker images. We just completely screwed because of the latest breaking change in latest without there being a new release of CrateDB that actually supports the new adapter

**Comment by chaudum** [comment]
Sorry to hear that.
We're about to introduce releases with this PR https://github.com/crate/crate_adapter/pull/16.

**Comment by amotl** [comment]
Hi all,

since version 0.2.0 issued on July 10, 2018, we are properly tagging this repository. Please note we are about to release 0.3.0 which introduces some minor, possibly breaking changes.

With kind regards,
Andreas.
