### ISSUE TITLE
Error executing write batch cannot convert [...] to Text

### ISSUE THREAD

**Issue by l-behrens** [crate/cratedb-prometheus-adapter#25]
Hello,
I updated the crate-adapter in a chain recently from 0.2.0 to 0.3.0 dev. In our previous configuration we used the http API of cratedb and switched to jdbc now.

Invoking the Adapter raises following errors.

```[root@adapter /]# /opt/remote_storage_adapter -config.file=/config/crate-adapter.yml -web.listen-address :9201
INFO[0000] Listening                                     address=":9201" source="server.go:419"
ERRO[0000] Failed to POST inserts to Crate.              err="error executing write batch: cannot convert 4679355392839385088 to Text" source="server.go:332"
ERRO[0000] Failed to POST inserts to Crate.              err="error executing write batch: cannot convert 4618441417868443648 to Text" source="server.go:332"
ERRO[0000] Failed to POST inserts to Crate.              err="error executing write batch: cannot convert 4657613057645618268 to Text" source="server.go:332"
ERRO[0000] Failed to POST inserts to Crate.              err="error executing write batch: cannot convert 0 to Text" source="server.go:332"
ERRO[0000] Failed to POST inserts to Crate.              err="error executing write batch: cannot convert 0 to Text" source="server.go:332"
ERRO[0000] Failed to POST inserts to Crate.              err="error executing write batch: cannot convert 4649658752004259840 to Text" source="server.go:332"
```

We use the suggested Metrics Table:

```
CREATE TABLE "metrics" (
    "timestamp" TIMESTAMP,
    "labels_hash" STRING,
    "labels" OBJECT(DYNAMIC),
    "value" DOUBLE,
    "valueRaw" LONG,
    "day__generated" TIMESTAMP GENERATED ALWAYS AS date_trunc('day', "timestamp"),
    PRIMARY KEY ("timestamp", "labels_hash", "day__generated")
  ) PARTITIONED BY ("day__generated");
```

and following adapter config:

```crate_endpoints:
- host: "crate"         # Host to connect to (default: "localhost").
  port: 5432                # Port to connect to (default: 5432).
  schema: "doc"      # Schema to use (default: "").
  max_connections: 5        # The maximum number of concurrent connections (default: 5).
  enable_tls: false         # Whether to connect using TLS (default: false).
  allow_insecure_tls: false # Whether to allow insecure / invalid TLS certificates (default: false).
```

CrateDB version is: 3.1.3

Is there some kind of data type Mapping incident using JDBC? Spent some hours but since I obviously need some help here.

Thanks a lot

**Comment by gianlucanatali** [comment]
Hi, thanks for the details. I have tried to reproduce this but was not able to.
To make this easier I have created a docker-compose file that configure a testing environment in a sandbox approach. Could you have a look [here](https://github.com/gianlucanatali/crate-prometheus-test) and try to reproduce your issue so we can have a look?
For our tests this adapter works for both CrateDB version 3.1.3 (as per your test) and 3.2.2 (latest version available as of today). Thanks

**Comment by amotl** [comment]
Dear Lars,

we are currently doing some spring cleaning here and look at closing outdated issues. However, in general we are still very much interested to find out what exactly caused this error on your end. We would probably need some sample data though in order to reproduce the issue.

So, please feel free to reopen or comment on this ticket anytime if you can add something to the discussion.

With kind regards,
Andreas.
