### ISSUE TITLE
Copy config.yml in Dockerfile

### ISSUE THREAD

**Issue by Haybu** [crate/cratedb-prometheus-adapter#29]
in Dockerfile file, doesn't it need config.yml to be copied? 

By adding the line below just before the last line.

COPY --from=builder /go/src/github.com/crate/crate_adapter/config.yml .

**Comment by fabianbaier** [comment]
I think you're right, see also https://github.com/gianlucanatali/crate-prometheus-test/blob/master/crate-prometheus-adapter/Dockerfile#L10

**Comment by amotl** [comment]
Dear Haytham and Fabian,

your suggestion has been implemented by @chaudum on behalf of 88611dae.

With kind regards,
Andreas.
