### ISSUE TITLE
HA mode?

### ISSUE THREAD

**Issue by lyc0221** [crate/cratedb-prometheus-adapter#32]
how to configure crate_adapter HA mode ?

**Comment by chaudum** [comment]
Hi @lyc0221 
Sorry for the late reply. Could you be a bit more specific about your question? What exactly do you mean with HA mode?
Thanks, Christian

**Comment by amotl** [comment]
_Thank you for writing in, and also sorry for the late reply. I am aiming to clean up some issues, and also found this one. I hope it will be safe to close it with my provided answer, but please let me know if you think differently._

### Prometheus HA
On this topic, I've discovered [^1]. Are you planning to make Prometheus highly available?

### CrateDB HA
If you are referring to the possibility of configuring multiple nodes of CrateDB instances, which form a cluster: Within the `config.yml` configuration file of this service, when multiple endpoints are listed, the adapter will load-balance between them.

[^1]: https://prometheus.io/docs/introduction/faq/#can-prometheus-be-made-highly-available
