### ISSUE TITLE
provide --version flag

### ISSUE THREAD

**Issue by jodok** [crate/cratedb-prometheus-adapter#7]
it would be great to see the version of crate_adapter installed by using the --version flag

**Comment by amotl** [comment]
Dear Jodok,

I am currently in the process of spring cleaning and thereby will close this ticket. Your wish has been implemented by @chaudum with e259a86b.

Running the command like this will emit the version information:
```
./cratedb-prometheus-adapter -version
```

With kind regards,
Andreas.
