### ISSUE TITLE
Prune previous OCI publishing location on Docker Hub

### ISSUE THREAD

**Issue by amotl** [crate/cratedb-prometheus-adapter#75]
## About

- Initial OCI image releases have been published at https://hub.docker.com/r/crate/crate_adapter.
- While improving CI with GH-42, we switched to publishing OCI images to GHCR, see https://ghcr.io/crate/cratedb-prometheus-adapter.

## Details

While everything is documented correctly on the README, we still may want to prune the project on Docker Hub.

## Q&A

If you agree, please add a 👍. If you have objections, 👎, optimally with a suggestion how to do it differently [^1].

[^1]: For example, by bringing back publishing to Docker Hub, for example. It will be a bit more effort needed to setup authentication properly. Using GHCR is just super convenient.

**Comment by seut** [comment]
+1 
Btw. even without pruning, we should ensure in future that people ending up on an old, deprecated place like the Docker Hub should get notified that this project has moved.

**Comment by amotl** [comment]
Do you have a suggestion how to pull that off? Maybe keep the documentation page there, let it refer to the new location, and purge the images only?

**Comment by seut** [comment]
I've added a note to the deprecated docker image registry that new images are available now on GHCR.
