### ISSUE TITLE
Error building query write_statement: mismatched param and argument count 

### ISSUE THREAD

**Issue by Elyspio** [crate/cratedb-prometheus-adapter#88]
Hello,

I'm using the image _ghcr.io/crate/cratedb-prometheus-adapter:nightly_ and i'm getting this error : 

`ts=2023-09-30T01:11:39.323Z caller=server.go:348 level=error msg="Failed to write data to CrateDB" err="error closing write batch: error building query write_statement: mismatched param and argument count (previously: error closing write batch: error building query write_statement: mismatched param and argument count; error closing write batch: error building query write_statement: mismatched param and argument count)"`

Versions : 
- Prometheus : v2.46.0
- cratedb-prometheus-adapter:nightly of the 2023/09/29
- cratedb : 5.4.3 or 4.8.0

**Comment by amotl** [comment]
Dear Jonathan,

thanks a stack for reporting. We made some changes recently, modernizing the application dependencies, and adding one or two features. While doing that, we have been convinced that the test suite provides enough coverage to support and verify the changes appropriately.

Now that you are reporting that the nightly OCI image apparently does not work at all, we need to revisit that, and of course fix the bug you are observing. If you are familiar with code, and you feel you could spot it easily, feel free to submit corresponding suggestions.

With kind regards,
Andreas.

**Comment by hlcianfagna** [comment]
Confimed with `git bisect` that the issue was introduced with https://github.com/crate/cratedb-prometheus-adapter/commit/a6831bc9011ccfa58c56d0ff7a5fb13d97b84b52

**Comment by amotl** [comment]
Dear Jonathan,

@hlcianfagna fixed the issue with GH-96: Thank you very much. Thus, I think the upcoming `nightly` release should work again. Otherwise, please let us know.

With kind regards,
Andreas.
